# Generated by Django 4.2 on 2025-10-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام طرف قرارداد')),
                ('category', models.CharField(choices=[('doctor', 'پزشک'), ('pharmacy', 'داروخانه'), ('store', 'فروشگاه')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('location_link', models.URLField(blank=True, help_text='مثلاً لینک گوگل مپ یا ویز', max_length=500, verbose_name='لینک لوکیشن روی نقشه')),
            ],
            options={
                'verbose_name': 'طرف قرارداد',
                'verbose_name_plural': 'طرف\u200cهای قرارداد',
            },
        ),
    ]
